spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon-system?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.enable_lazy_load_no_trans: true
